name: Build and Release QGIS Plugin

on:
  push:
    tags:
      - 'v*'  # Triggers only when pushing tags like v1.0.0, v2.1.3, etc.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Correct syntax

      - name: Zip the plugin
        run: |
          mkdir -p release
          zip -r release/qgis_plugin_gpq_downloader.zip * -x ".git*" ".github*" "release*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4  # Correct syntax
        with:
          name: qgis-plugin-release
          path: release/qgis_plugin_gpq_downloader.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Correct syntax

      - name: Download zipped plugin
        uses: actions/download-artifact@v4  # Correct syntax
        with:
          name: qgis-plugin-release
          path: .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1  # Correct syntax
        with:
          files: qgis_plugin_gpq_downloader.zip
          body: "Automated release of QGIS plugin for Overture Maps."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
