name: Build and Release QGIS Plugin

on:
  push:
    tags:
      - 'v*'  # Triggers only when pushing tags like v1.0.0, v2.1.3, etc.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to v4

      - name: Zip the plugin
        run: |
          mkdir -p release
          zip -r release/qgis_plugin_gpq_downloader.zip * -x ".git*" ".github*" "release*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: qgis-plugin-release
          path: release/qgis_plugin_gpq_downloader.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to v4

      - name: Download zipped plugin
        uses: actions/downl
